class01/README.md
class02/README.md

[Class01 HW#3] Github PR 실습 - Table 수정-YuNyuk

---

class01/README.md
class02/README.md

[Class01 HW#3] Github PR 실습 - Table 수정 - 정용재

---

class01/README.md
class02/README.md

[Class01 HW#3] Github PR 실습 - 김윤우

---

class01/README.md
class02/README.md

Change table and Create new PR

[Class01 HW#3] Github PR 실습 - Table 수정 - 김가현

---

class01/README.md
class02/README.md

Class01 HW#3 GitHub 수정을 위한 issue 입니다
05번 이름, github id 변경 했습니다.

[Class01 HW#3] Github PR 실습 - 김기범

---

class01/README.md
class02/README.md

[Class01 HW#3] Github PR 실습 - 김기훈

---

class01/README.md
class02/README.md

[Class01 HW#3] Github PR 실습 - 차창섭

---

class01/README.md
class02/README.md

README.md 안에 테이블 11번 조원진 수정

---

class01/README.md
class02/README.md

* Title / Comment
class*/README.md 파일의 테이블 내용을 수정
* 6번째 칸에 YeomJaeYoung / wodud6423수정 
* Assignees - wodud6423(yourself)
* Milestone - [Class01 HW#3] Github PR 실습 - Table 수정

[Class01 HW#3] Github PR 실습 - Table 수정 염재영

---

class01/README.md
class02/README.md

[Class01 HW#3] Github PR 실습 - Table 수정 - 이성우

---

class01/README.md
class02/README.md

Class 01 hw2 jowonjin96

---

class01/mini-project/04_Mini_Project_JWJ_JYJ/README.md

[4조 Mini-Project first commit]

---

class01/mini-project/07_Chanuk,MinjeungA/README.md

mini07-HeoChanuk

---

class01/README.md

Class01 Readme 수정

---

class01/mini-project/02_kim_yeom/README.md

2조 Update README.md(프로젝트 시연 결과에 오디오 파일추가)

2조 Update README.md(프로젝트 시연 결과에 오디오 파일추가)

---

class02/homework/KwonOhjoon/hw1-arduino-basic/led.py

Add KwonOhjoon class02 hw1 file

---

class02/homework/yj_jung/hw1/led.py

과제1 Arduino와 Python을 이용한 LED제어 - 정용재

과제1 Arduino와 Python을 이용한 LED제어 - 정용재

---

class02/homework/ChoiJaeHyeok/hw1/led.py

과제1 Arduino와 Python을 이용한 LED제어 - 최재혁

Class02_hw1_CJH

---

class02/homework/yeomjaeyoung/led.py

과제1 Arduino와 Python을 이용한 LED제어 - 염재영

과제1 Arduino와 Python을 이용한 LED제어 - 염재영

---

class02/homework/chachangseop/hw1/led.py

class02-hw1-chachangseop

---

class02/homework/kimgibeom/hw1/led.py

과제1 Arduino와 Python을 이용한 LED제어 - 김기범

---

class02/homework/jiwonlee/hw1/led.py

과제1 Arduino와 Python을 이용한 LED제어 - 이지원

---

class02/homework/kihoon/hw1/led.py

class02-hw1-kihoon

---

class02/homework/chachangseop/hw3/DeiT-Tiny/openvino.xml
class02/homework/chachangseop/hw3/EfficientNet-B0/openvino.xml
class02/homework/chachangseop/hw3/EfficientNet-V2-S/openvino.xml
class02/homework/chachangseop/hw3/MobileNet-V3-large-1x/openvino.xml
class02/homework/chachangseop/hw3/hw03_template.md

class02-hw3-chachangseop

---

class02/homework/KwonOhjoon/hw3/DeiT-Tiny/model.bin
class02/homework/KwonOhjoon/hw3/DeiT-Tiny/model.xml
class02/homework/KwonOhjoon/hw3/EfficientNet-B0/model.bin
class02/homework/KwonOhjoon/hw3/EfficientNet-B0/model.xml
class02/homework/KwonOhjoon/hw3/EfficientNet-V2-S/model.bin
class02/homework/KwonOhjoon/hw3/EfficientNet-V2-S/model.xml
class02/homework/KwonOhjoon/hw3/MobileNet-V3-large-1x/model.bin
class02/homework/KwonOhjoon/hw3/MobileNet-V3-large-1x/model.xml
class02/homework/KwonOhjoon/hw3/README.md

Add class02 hw2 files

---

class02/homework/jiwonlee/hw3/DeiT-Tiny/openvino.bin
class02/homework/jiwonlee/hw3/DeiT-Tiny/openvino.xml
class02/homework/jiwonlee/hw3/EfficientNet-B0/openvino.bin
class02/homework/jiwonlee/hw3/EfficientNet-B0/openvino.xml
class02/homework/jiwonlee/hw3/EfficientNet-V2-S/openvino.bin
class02/homework/jiwonlee/hw3/EfficientNet-V2-S/openvino.xml
class02/homework/jiwonlee/hw3/MobileNet-V3-large-1x/openvino.bin
class02/homework/jiwonlee/hw3/MobileNet-V3-large-1x/openvino.xml
class02/homework/jiwonlee/hw3/README.md

Class02 과제3 OTX를 이용한 model training - 이지원

---

README.md

[Intel 프로젝트 2조] README.md 수정

---

README.md

Team E-Z Kiosk edited 

---

class02/homework/kimgibeom/hw3/EfficientNet-B0/openvino.xml
class02/homework/kimgibeom/hw3/MobileNet-V3-large-1x/openvino.xml
class02/homework/kimgibeom/hw3/README.md

과제3 OTX를 이용한 model training - 김기범

---

class02/homework/KwonOhjoon/hw4/factory.py

Class02 HW4 파일 제출
Pylint score : 9.62/10

Add KwonOhjoon class02 hw4 file

---

class02/homework/YouKwangGyun/hw1/led.py

class02-hw1-ykg

---

class01/README.md

miniproject team05 modify class01/README.md

miniproject team05 modify

---

class01/mini-project/09_jhj_kkh/README.md

class01- 09 - Update README.md

class01- 09 - Update README.md

---

doc/project/Team4_D-gaja/README.md

team4_D-gaja_final

---

README.md
doc/project/Team_7/README.md

오픈비노 프로젝트 팀7 가오가이거 README 업데이트

team7_README_updated

---

README.md

main page README.md 파일의 ppt 파일 link 수정하였습니다.
늦어서 죄송합니다.

team06 PPT link update
